steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/docker-gce-app', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/docker-gce-app']

  # Step 3: SSH into the GCE instance and deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'gce-instance-name'
      - '--zone=us-central1-a'  # Specify your instance's zone here
      - '--command=sudo docker pull gcr.io/$PROJECT_ID/docker-gce-app && sudo docker run -d -p 80:8080 gcr.io/$PROJECT_ID/docker-gce-app'

images:
  - 'gcr.io/$PROJECT_ID/docker-gce-app'
